kind: Template
apiVersion: v1
template: yolo
metadata:
  name: yolo
objects:

- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPNAME}
    labels:
      name: ${APPNAME}
  spec:
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      name: ${APPNAME}

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPNAME}
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      name: ${APPNAME}
    template:
      metadata:
        labels:
          name: ${APPNAME}
      spec:
        containers:
          - name: ${APPNAME}
            image: docker.io/willb/imagescorer:latest
            ports:
              - containerPort: 8080
                protocol: TCP
            readinessProbe:
              httpGet:
                path: /v2/ui/
                port: 8080
              initialDelaySeconds: 15
              timeoutSeconds: 1

parameters:
  - name: APPNAME
    description: the application name
    value: yolo
  - name: ROUTE_HOSTNAME
    description: a hostname for the route